In [1]:
import numpy as np


In [3]:
data = np.random.rand(10,2)

In [6]:
data

array([[0.38250626, 0.47710842],
       [0.06804447, 0.67905177],
       [0.30426776, 0.38733615],
       [0.1512292 , 0.57159859],
       [0.46431301, 0.3012122 ],
       [0.6996288 , 0.0891823 ],
       [0.31283163, 0.95327801],
       [0.85195765, 0.43173639],
       [0.00935728, 0.21672897],
       [0.29033498, 0.54066562]])

In [5]:
data[:,0]*

array([0.38250626, 0.06804447, 0.30426776, 0.1512292 , 0.46431301,
       0.6996288 , 0.31283163, 0.85195765, 0.00935728, 0.29033498])

In [21]:
a = np.random.randint(0, 1281, (10))
b = np.random.randint(0, 721, (10))

In [22]:
a

array([1062, 1126,  581,  712,   62, 1228, 1152,   94,  805, 1216])

In [23]:
b

array([562, 166,  53, 651,  24, 362,  60, 199, 226, 576])

In [24]:
[a,b]

[array([1062, 1126,  581,  712,   62, 1228, 1152,   94,  805, 1216]),
 array([562, 166,  53, 651,  24, 362,  60, 199, 226, 576])]

In [30]:
np.stack((a,b)).T

array([[1062,  562,  562],
       [1126,  166,  166],
       [ 581,   53,   53],
       [ 712,  651,  651],
       [  62,   24,   24],
       [1228,  362,  362],
       [1152,   60,   60],
       [  94,  199,  199],
       [ 805,  226,  226],
       [1216,  576,  576]])

In [13]:
np.random.randint(0, 2, (10,1))

array([[0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0]])

In [33]:
np.random.randint(0,2,10)

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [35]:
event_type = np.random.randint(0,500,500)

In [36]:
event_type.dtype

dtype('int64')

In [42]:
%timeit np.random.randint(0,500,500)

4.36 µs ± 43 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [52]:
def create_and_sort_values(n):
    return np.sort(np.random.randint(0,500,n))

In [60]:
%timeit data = create_and_sort_values(500)

23.7 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [47]:
from numba import jit

In [61]:
@jit(nopython=True)
def create_and_sort_values_numba(n):
    return np.sort(np.random.randint(0,500,n))

In [74]:
%timeit create_and_sort_values_numba(500)

15.1 µs ± 348 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [75]:
data = create_and_sort_values_numba(500)

In [76]:
data

array([  0,   0,   3,   5,   6,   7,   8,   8,   9,   9,  10,  12,  16,
        17,  17,  17,  18,  18,  19,  20,  24,  25,  26,  27,  29,  29,
        31,  32,  32,  32,  33,  33,  34,  34,  35,  35,  37,  38,  38,
        39,  39,  40,  40,  41,  43,  46,  49,  50,  51,  53,  53,  55,
        56,  56,  57,  58,  58,  59,  59,  60,  60,  60,  62,  62,  62,
        63,  64,  65,  66,  66,  69,  69,  70,  70,  70,  70,  73,  73,
        74,  75,  75,  76,  76,  80,  81,  83,  84,  85,  89,  90,  90,
        90,  91,  91,  92,  95,  96,  97,  98,  99,  99,  99, 101, 103,
       106, 107, 107, 107, 107, 108, 108, 109, 110, 112, 113, 113, 113,
       116, 116, 117, 119, 119, 120, 123, 124, 124, 124, 125, 126, 127,
       130, 131, 132, 133, 134, 136, 136, 137, 137, 139, 139, 139, 140,
       140, 140, 142, 144, 146, 148, 148, 148, 148, 149, 150, 150, 150,
       153, 157, 157, 157, 158, 162, 164, 166, 166, 166, 167, 168, 169,
       170, 173, 175, 175, 176, 179, 181, 181, 182, 182, 182, 18

np.sort(np.random.randint(0,2000,50))

In [84]:
testdata = np.random.randint(0,2000,(4,10)).T

In [85]:
testdata

array([[1622,  568, 1364,  865],
       [ 968,  218,  719,  782],
       [1940,  692,  255,  563],
       [1767, 1231,  917,  844],
       [ 176,  537,  536,  637],
       [1683,  893,  542, 1658],
       [ 246, 1577,  258, 1702],
       [1727,  835,  156,  374],
       [  33, 1451, 1671, 1582],
       [1425,  977,  142, 1549]])

In [92]:
testdata[:,0]

array([1622,  968, 1940, 1767,  176, 1683,  246, 1727,   33, 1425])