In [1]:
import numpy as np

In [3]:
data = np.random.rand(10,2)

In [6]:
data

array([[0.38250626, 0.47710842],
       [0.06804447, 0.67905177],
       [0.30426776, 0.38733615],
       [0.1512292 , 0.57159859],
       [0.46431301, 0.3012122 ],
       [0.6996288 , 0.0891823 ],
       [0.31283163, 0.95327801],
       [0.85195765, 0.43173639],
       [0.00935728, 0.21672897],
       [0.29033498, 0.54066562]])

In [5]:
data[:,0]*

array([0.38250626, 0.06804447, 0.30426776, 0.1512292 , 0.46431301,
       0.6996288 , 0.31283163, 0.85195765, 0.00935728, 0.29033498])

In [11]:
np.random.randint(0, 1281, (10,2))

array([[1194,  612],
       [ 664, 1003],
       [ 200,  731],
       [ 297,  526],
       [ 890,  524],
       [ 163,   82],
       [1214, 1002],
       [1200,  712],
       [ 965,  102],
       [1098, 1068]])

In [13]:
np.random.randint(0, 2, (10,1))

array([[0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0]])

In [ ]:
data = np.random.rand(500,2)