In [ ]:
np.random.randint(

In [1]:
import numpy as np

In [11]:
print(np.random.randint(-10,10,10))

[  6 -10  -4  -8 -10  -3  -8  -1  -3   5]


In [13]:
print(np.random.randint(-10,10,(10,2)))

[[ -7  -3]
 [  2   3]
 [  2   9]
 [ -9   0]
 [-10  -3]
 [ -2 -10]
 [ -2  -2]
 [ -9  -6]
 [ -6  -4]
 [ -9   6]]


In [28]:
mymatrix = np.random.randint(-10,10,(10,4))

In [29]:
mymatrix

array([[ -1,  -4,   6,   4],
       [  3, -10,  -7,   6],
       [  4,   1,  -1,   0],
       [ -1,   4,   2,  -1],
       [ -8,   5, -10,   6],
       [ -6,   9,   6,   6],
       [  5,   9,   4,  -8],
       [  6,   7,  -7,   0],
       [ -4,  -4,   5,  -8],
       [ -3,  -6,  -1,   9]])

In [32]:
mymatrix[:,0:2]

array([[ -1,  -4],
       [  3, -10],
       [  4,   1],
       [ -1,   4],
       [ -8,   5],
       [ -6,   9],
       [  5,   9],
       [  6,   7],
       [ -4,  -4],
       [ -3,  -6]])

In [19]:
np.mean(mymatrix, axis=0)

TypeError: only size-1 arrays can be converted to Python scalars

In [35]:
np.divide(np.mean(mymatrix[:,0:2], axis=0),[2,3])

array([-0.25      ,  0.36666667])